### ISSUE TITLE
Error when running franka_example_controller move_to_start.launch

### ISSUE THREAD

**Issue by Innoconnect** [frankaemika/franka_ros#100]
Hi, I installed libfranka and frankaros from source, and I can successfully run the /libfranka/build/examples/communication_test, running the franka_visualization.launch is fine, I can see the realtime movement in RVIZ, also control the franka from desk is fine, but when I run the move_to_start.launch, it never works.
It seems like the motion planning error, '[ERROR] [1584944110.922779894]: RRTConnect: Motion planning start tree could not be initialized!'could you please help me? 

Below is the information shown in my terminal, Thanks.
silu@hrc:~/libfranka/build/examples$ roslaunch franka_example_controllers move_to_start.launch robot_ip:=192.168.3.133
[ INFO] [1584944110.896784661]: Planning attempt 1 of at most 1
[ INFO] [1584944110.897732900]: Found a contact between 'panda_link7' (type 'Robot link') and 'panda_link5' (type 'Robot link'), which constitutes a collision. Contact information is not stored.
[ INFO] [1584944110.897771119]: Collision checking is considered complete (collision was found and 0 contacts are stored)
[ INFO] [1584944110.897805134]: Start state appears to be in collision with respect to group panda_arm
[ WARN] [1584944110.920389200]: Unable to find a valid state nearby the start state (using jiggle fraction of 0.050000 and 100 sampling attempts). Passing the original planning request to the planner.
[ INFO] [1584944110.922163893]: Planner configuration 'panda_arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[ WARN] [1584944110.922726541]: RRTConnect: Skipping invalid start state (invalid state)
[ERROR] [1584944110.922779894]: RRTConnect: Motion planning start tree could not be initialized!
[ INFO] [1584944110.922815894]: No solution found after 0.000137 seconds
[ INFO] [1584944110.922985918]: Unable to solve the planning problem
[ INFO] [1584944110.923442040]: ABORTED: No motion plan found. No execution attempted.

**Comment by Innoconnect** [comment]
I reinstalled all of the package again, panda_moveit_config, franka_ros, and moveit, afterwards the problem was solved.

**Comment by Simon-Fuhaoyuan** [comment]
Hello! I also faced your problem, completely the same. However, after reinstalling all these packages again, I still cannot fix this bug. Can you please explain how you install these packages in detail? For example, you install these packages in binary or from source?
